### ISSUE TITLE
JSDom is overkill

### ISSUE THREAD

**Issue by jefflembeck** [filamentgroup/directory-colorfy#12]
Let's use libxml2 for this

**Comment by weshardee** [comment]
Another reason to avoid JSDom: it uses contextify which seems to have issues with Windows (the first line of their readme is about Windows issues). I had to roll back to an earlier version of grunticon on a project just to avoid this dependency.

**Comment by jefflembeck** [comment]
Ouch. Ok. Looks like libxmljs is out for this as well (as using it for Windows seems to be an issue)

I'll get a better fix in soon.

**Comment by jefflembeck** [comment]
Using phantom instead. It has far better cross compat with windows
