### ISSUE TITLE
Processed SVGs Comment Out XML Headers

### ISSUE THREAD

**Issue by levineuland** [filamentgroup/directory-colorfy#14]
When the SVG file passes through /lib/phantomscript.js to replace colors the output also comments out any provided xml header.

Without that header Windows 7 doesn't recognize it as a valid SVG file which causes it to output text instead of the rendered image when using svg-to-png converters.

Attached screenshots show the original icon and one after being processed by directory-colorfy on Windows 7. I confirmed that by manually adding an XML header it allows the file to be processed as normal.

![arrow-left](https://cloud.githubusercontent.com/assets/1440716/6063200/67894c34-ad23-11e4-80af-c090b0e1fe17.png)
![arrow-left-black](https://cloud.githubusercontent.com/assets/1440716/6063199/67832eee-ad23-11e4-8d5a-2eb5e3e7f5f5.png)

**Comment by jefflembeck** [comment]
Hrm, I've seen this issue several times when svgmin is in place. I'll see what I can grab. Thanks

**Comment by jefflembeck** [comment]
Ok, the xml header is no longer commented out in 2.0.1
