### ISSUE TITLE
Can the non-scoped 'worker-farm' dependency be used?

### ISSUE THREAD

**Issue by mattdsteele** [filamentgroup/directory-colorfy#17]
I'm using Grunticon in a corporate environment; and we run a private NPM registry through a tool called [Nexus](http://blog.sonatype.com/2014/10/npm-registry-support-for-all/).

This works great, except that [private/scoped modules are not yet supported in Nexus](https://issues.sonatype.org/browse/NEXUS-6857). As such, we can't use Grunticon due to its transitive dependency on `@filamentgroup/worker-farm`.

Is there a reason the non-scoped [worker-farm](https://www.npmjs.com/package/worker-farm) module can't be used? I tried swapping it out in `package.json` and running the tests; they're stalling, but I can't tell if that's a result of my environment or not.

I know this isn't directly your issue; Nexus needs to support scoped modules. But making this change would help us out quite a bit.

Let me know if there's anything I can do to help - thanks!

**Comment by jefflembeck** [comment]
As of right now, unfortunately - the scoped module is necessary. We had to make changes to worker farm to make it work within the context of this project.

That being said, I know that @johnbender was taking a look at making our changes something he could PR into the main project.

**Comment by zachleat** [comment]
Hi @mattdsteele. Looks like that Nexus issue is closed? For future maintenance I’ve filed this task as #30 so please follow along over there—thanks!

**Comment by mattdsteele** [comment]
Yup, not an issue for us anymore, so feel free to fix on your own timeline!
