### ISSUE TITLE
phantomjs-1.9.15 version-hardcoded dependency needed?

### ISSUE THREAD

**Issue by lkraav** [filamentgroup/directory-colorfy#20]
Is there too much risk accepting ^1.9.15? As it is, `directory-colorfy` and `svg-to-png` build two different instances of `phantomjs` simply due to the version lock.

**Comment by jefflembeck** [comment]
`^1.9.15` means that `directory-colorfy` will accept all phantom versions that are at least 1.9.15, but < 2.x

The way npm handles versions of phantom, `directory-colorfy` and `svg-to-png` do not use the same build, unless you are using npm 3, and the versions downloaded are the exact same.
