### ISSUE TITLE
re-publish to npm

### ISSUE THREAD

**Issue by craig-mulligan** [filamentgroup/directory-colorfy#25]
The directory-colorfy npm package doesn't reflected the latest change merged here - https://github.com/filamentgroup/directory-colorfy/commit/761c2541bf5a7f5da663807b6347428956e70702 

This means I occasionally get install errors associated with phantom.js v1. see here: https://github.com/Medium/phantomjs/issues/552

Could you republish to npm?

**Comment by johnbender** [comment]
Done! 2.1.0 is up with an updated version of our `node-worker-farm` fork.

**Comment by craig-mulligan** [comment]
Appreciate it! 👍
