### ISSUE TITLE
Loosen restriction on supported phantomjs-prebuilt versions

### ISSUE THREAD

**Issue by bostaunieux** [filamentgroup/directory-colorfy#27]
I'm attempting to convert a project, which relies on this package via grunt-grunticon, to use yarn and there are known issues with yarn and phantomjs-prebuilt version 2.1.7 (https://github.com/yarnpkg/yarn/issues/1538).

I've been able to modify yarn's configuration to force this project to use phantomjs-prebuilt 2.1.14, but the edits are a mess.

Ideally, this project would loosen it's restriction to support a range of phantomjs-prebuilt versions, so that manual override wouldn't be necessary.

Sample semver range that mirrors what [svg-to-png](https://github.com/filamentgroup/svg-to-png) uses: 

```
  "phantomjs-prebuilt": "^2.1.7"
```

**Comment by jefflembeck** [comment]
I agree wholeheartedly. I think this may have been an oversight on our behalf.
